baseurl = "//uvasrg.github.io/"
languageCode = "en-us"
title = "Security Research Group"
copyright = "Privacy and Security Research at the University of Virginia"
theme = "srg"

paginate = 10
paginatePath = "page"

pageNotFoundTitle = "Not Found"
pageNotFoundDetail = "Your request was determined to be an adversarial example by our web server. This could be because you are evil, but it is most likely a bad link or mistyped URL."

# disqusShortname = "evans1629"

[markup.goldmark.renderer]
unsafe= true

[permalinks]
    post = "/:slug/"
    code = "/:slug/"

[params]
    brand = "Security Research Group"
    topline = "University of Virginia Security Research Group"
    footline = "<p align=\"center\">University of Virginia | Privacy and Security Research Group</p>"
    sidebar = "left"

    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[taxonomies]
  category = "categories"
  tag = "tags"

[blackfriday]
    angledQuotes = false
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[[menu.footer]]
